$pdf_mode = 1;
$interaction = 'nonstopmode';
$halt_on_error = 1;
$pdflatex = 'pdflatex -shell-escape %O %S';
$ENV{'TEXINPUTS'} = 'template/acmart//:' . ($ENV{'TEXINPUTS'} // '');
$ENV{'BSTINPUTS'} = 'template/acmart//:' . ($ENV{'BSTINPUTS'} // '');
